/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

	public static void main(String[] args) {
		Vehicle a = new Vehicle("car a", "Benz");
		a.speedUp(30);
		Vehicle b = new Vehicle("car b", "Audi");
		b.speedUp(40);
		
		Car car = new Car("My Car", "Goodby");
		car.speedUp(180);
		car.speedUp(201);
    }
}
