/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Vehicle {
	
	public String name;
	public String brand;
	
	public Vehicle (String name, String brand) {
		this.name = name;
		this.brand = brand;
	}
	
	public void speedUp (int increase) {
		System.out.println(this.brand + " " + this.name + " has been speeded up to " + increase);
	}
	public static void main(String[] args) {
		Vehicle a = new Vehicle("car a", "Benz");
		a.speedUp(30);
		Vehicle b = new Vehicle("car b", "Audi");
		b.speedUp(40);
    }
}
